apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
      version: v1
  template:
    metadata:
      labels:
        app: sampleapp
        version: v1
    spec:
      containers:
      - name: sampleapp
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: sampleapp-v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sampleapp
    version: v1
  name: sampleapp-v1
data:
  index.html: |-
    <html>
    <head>
      <title>V1</title>
    </head>
    <body>
      <h1 style="color: #0000ff">V1</h1>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-v1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: sampleapp
    version: v1